Remove node js version 4 support.
According to the [Node 6 release announcement](https://nodejs.org/en/blog/release/v6.0.0/)
Version 4 is now in Maintenance mode as of April 2017. It is also very
slow to build on travis. Finally, in a [PR 371](https://github.com/alsatian-test/alsatian/pull/371)
a [runtime syntax error](https://travis-ci.org/alsatian-test/alsatian/jobs/229130470)
is occurring because a default function parametersyntax is illegal in
the version of V8 being used:
```
/home/travis/build/alsatian-test/alsatian/node_modules/traceloc/out/traceloc.js:35
function here(callDepth = 0) {
                        ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
```

I'm sure it could be made to run, but this seems a reasonable approach.