Remove most errors in core/running/test-runner.ts
There are still three `used before being assigned` errors:

  core/running/test-runner.ts(86,38): error TS2454: Variable 'currentTestFixtureResults' is used before being assigned.
  core/running/test-runner.ts(93,26): error TS2454: Variable 'currentTestResults' is used before being assigned.
  core/running/test-runner.ts(97,26): error TS2454: Variable 'currentTestResults' is used before being assigned.

See branch `WIP-stricter-tsc-options-test-runner-coverage-fix-needed` for
a "solution" that needs coverage fixes. Leaving this for later.